export const ADD_TO_CART = "ADD_TO_CART";

export const INCREASE_IN_CART = "INCREASE_IN_CART";

export const DECREASE_IN_CART = "DECREASE_IN_CART";

export const DELETE_FROM_CART = "DELETE_FROM_CART";